site:
  title: Documentation
  url: http:localhost:5000
  start_page: cloud::overview.adoc
  keys:
    google_analytics: 'GTM-MQ59XD6'
    docsearch_id: 'QK2EAH8GB0'
    docsearch_api: 'ef7bd9485eafbd75d6e8425949eda1f5'
    docsearch_index: 'prod_hazelcast_docs'
content:
  sources: 
  - url: .
    branches: HEAD
    start_paths:
    - ./docs
    - ./tutorials
  - url: https://github.com/hazelcast/hazelcast-cloud-code-samples
    branches: master
    start_paths:
    - spring-sample/docs
    - client-failover/client-failover-sample-hazelcast5/docs
    - mapstore/mapstore-sample-hazelcast5-mongodb/docs
    - serverless-fraud-detection/docs
    - compute/standard-deviation/docs
  - url: https://github.com/hazelcast/hazelcast-cloud-maven-plugin
    branches: serverless-mvp-uat
    start_path: docs
  - url: https://github.com/hazelcast/management-center-docs
    branches: [main]
    start_path: docs
ui: 
  bundle:
    url: ../hazelcast-docs-ui/build/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    page-pagination: true
    idprefix: ''
    idseparator: '-'
    hazelcast-cloud: Hazelcast Viridian
  extensions:
    - ./lib/tabs-block.js
    - asciidoctor-kroki
