site:
  title: Documentation
  url: http:localhost:5000
content:
  sources: 
  - url: .
    branches: HEAD
    start_paths: [./docs, ./tutorials]
  - url: https://github.com/hazelcast/imdg-docs
    branches: [master, v/*]
    start_path: docs
  - url: https://github.com/hazelcast/imdg-docs
    branches: [archived-versions]
    start_paths: docs/*
  - url: https://github.com/hazelcast/management-center-docs
    branches: [main, v/*]
    start_path: docs
  - url: https://github.com/hazelcast/management-center-docs
    branches: [archived-versions]
    start_paths: docs/*
  - url: https://github.com/hazelcast/hz-docs
    branches: [main, v/*]
    start_path: docs
  - url: https://github.com/hazelcast/hazelcast-cloud-code-samples
    branches: master
    start_paths:
    - spring-sample/docs
    - client-failover/client-failover-sample-hazelcast5/docs
    - mapstore/mapstore-sample-hazelcast5-mongodb/docs
  - url: https://github.com/hazelcast/hazelcast-cloud-code-samples
    branches: aws-tutorial
    start_path: serverless-fraud-detection/docs
  - url: https://github.com/hazelcast/hazelcast-cloud-code-samples
    branches: standard-deviation
    start_path: compute/standard-deviation/docs 
  - url: https://github.com/hazelcast/hazelcast-cloud-maven-plugin
    branches: serverless-mvp-uat
    start_path: docs
ui: 
  bundle:
    url: https://github.com/hazelcast/hazelcast-docs-ui/releases/download/v3.1-beta/ui-bundle.zip #../hazelcast-docs-ui/build/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    page-pagination: true
    idprefix: ''
    idseparator: '-'
    hazelcast-cloud: Hazelcast Viridian
  extensions:
    - ./lib/tabs-block.js
    - asciidoctor-kroki
